### ISSUE TITLE
Integration with solr

### ISSUE THREAD

**Issue by nisha-kajale** [atilika/kuromoji#87]
Hi,
I am new to solr. I have downloaded kuromoji
And placed it in solr-5.3.0\server\lib 
And added 
<fieldType name="text_ja" class="solr.TextField">
      <analyzer>
        <tokenizer class="org.atilika.kuromoji.solr.KuromojiTokenizerFactory"
                   mode="search"
                   user-dictionary=""/>
      </analyzer>
    </fieldType>
in solr-5.3.0\server\solr\configsets\basic_configs\conf
Now if i do search it should treat each of search term as japanese right?
Or do i need to specify which text should be treated as japanese

**Comment by cmoen** [comment]
Apache Solr already is already bundled with JapaneseTokenizer (based on Kuromoji) since version 3.6.  Simply use field type `text_ja` and you should be able to search Japanese just fine.  There's no need to put any jars anywhere to use Japanese - it works out-of-the-box.

See https://speakerdeck.com/atilika/japanese-linguistics-in-lucene-and-solr for more information on features, etc.

**Comment by nisha-kajale** [comment]
hi ,

Thanks for quick reply.
Can you tell me where should i write this text_ja 
in schema.xml or solrconfig.xml of my core
And also if schema.xml which file should i use. As there are several schema.xml

**Comment by cmoen** [comment]
Please have a look at the Apache Solr documentation on https://cwiki.apache.org/confluence/display/solr/Getting+Started for further details. Thanks.
